# Generated by Django 2.1.4 on 2019-03-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('createdby', models.CharField(max_length=200)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_highestrated', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pixma.Department')),
            ],
        ),
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture', models.CharField(max_length=200)),
                ('lecturelink', models.TextField()),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixma.Course')),
            ],
        ),
    ]
