# Generated by Django 2.1.4 on 2019-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixma', '0002_course_tablecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=244),
        ),
    ]
